name: This is Me
favicon: null
layout_spectrum: 0.98307
typography_spectrum: 0.50549
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#545454'
    - '#a8978d'
    - '#c6c4c5'
    - '#81286c'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.4375
  rhythmicContrast: 1
purpose: []
