name: This is Me
favicon: null
layout_spectrum: 0.10252724844031036
typography_spectrum: 0.6113143675029278
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c9cdce'
    - '#898ea4'
    - '#79584f'
    - '#5fc363'
    - '#2e2c2d'
  brandStrength: 0.5485909753479064
  lightness: 0.4455991720315069
  saturation: 0.367101538926363
  rhythmicContrast: 0
purpose: []
